documentation:
- changed-files:
  - any-glob-to-any-file:
    - 'docs/**'
    - 'README.md'
    - 'CHANGELOG.md'

ci:
- changed-files:
  - any-glob-to-any-file: '.github/workflows/**'

tests:
- changed-files:
  - any-glob-to-any-file:
    - 'tests/**'
    - 'debug/**'

scripts:
- changed-files:
  - any-glob-to-any-file: 'scripts/**'

config:
- changed-files:
  - any-glob-to-any-file:
    - 'config/**'
    - 'systemd/**'

python:
- changed-files:
  - any-glob-to-any-file:
    - 'src/**'
    - 'pyproject.toml'
    - 'requirements*.txt'
